K8s:
  pipelineName: k8s_deployment
  chart: 
    repo: urs-helm
    repoPromotion1: urs-helm-release-local
    name: myapp
    version: 0.1.0
  integration:
    artifactory: artifactory_eu
    k8s: yann_k8s
  namespace: build-plane

K8sResources:
  gitRepoHelm:
    name: src_code_helm
    gitProvider: my_github
    path: cyan21/su301
    branches:
      include: lab3_ok
    files:
      include: cd\/k8s/.*\.yml
  chart:
    name: lab3_hc
  buildInfo:
    resourceName: lab3_bi_chart
    name: k8s_helm_chart
  buildInfoPromoted:
    resourceName: lab3_bi_chart_promoted

K8sSteps:
  publishHelm:
    name: lab3_publish_helm_chart
    path: cd/k8s/helm_chart/
    lint: true
    autoPublishBuildInfo: true
  deployHelm:
    name: lab3_deploy_helm_chart
  testApp:
    name: lab3_test_app
  promoteHelm:
    name: lab3_promote_helm_chart
    includeDependencies: false
    status: TEST_OK
    comment: passed non regression test
    copy: false



