Init:
  pipelineName: k8s_project_init
  container:
    # for Docker build
    registry: platform-us.staging.gcp.devopsacc.team/stn-docker
    image: jfrog/pipelines-u18node
    tag: 10.21.0-jfrog
    # repoSource and repoPromotion have to be local repo (due to the JFrog CLI limitation)
    repoSource: stn-docker-release-local
  chart:
    repo: stn-helm
    name: myapp
    version: 1.0.0
  artifactoryIntegration: artifactory_eu

InitResources:
  gitRepo:
    name: src_code_k8s_app
    gitProvider: yann_github
    path: cyan21/k8s-app
    branches:
      include: soleng-stg
    files:
      include: ^chart\/CI\/jfrog\/.+
  gitRepoDocker:
    name: src_dockerfile_base_image_helm
    gitProvider: yann_github
    path: cyan21/k8s-app
    branches:
      include: soleng-stg
    files:
      include: ^chart\/CI\/jfrog\/Dockerfile
  gitRepoHelm:
    name: src_code_k8s_helm
    gitProvider: yann_github
    path: cyan21/k8s-app
    branches:
      include: soleng-stg
    files:
      include: ^chart\/content\/.+
  buildInfoContainer:
    resourceName: bi_base_image_helm
    name: helm_base_image
  buildInfoHelm:
    resourceName: bi_hc_my_app
    name: helm_chart_myapp
  chart:
    resourceName: hc_my_app
    name: myapp
    version: 1.0.0
    repo: stn-helm

InitSteps:
  publishHelm:
    name: publish_helm_chart
    path: chart/content/
    lint: true
    autoPublishBuildInfo: true
  dockerBuild:
    name: build_helm_base_image
    dockerFileName: Dockerfile
    dockerFileLocation: chart/CI/jfrog/
  dockerPush:
    name: publish_helm_base_image
    autoPublishBuildInfo: true
    forceXrayScan: false


Chart:
  pipelineName: k8s_bump_helm_chart
  # It's either Chart + Docker OR Docker distribution (see back/CI/jfrog/pipelines/values/yml  > BackApp.distribute)
  distribute: true
  # # TO DO  : REMOVE THE CUSTOM IMAGE IN THE LATEST VERSION OF PIPELINE
  # container:
  #   registry: iot-soleng-stg.gcp.devopsacc.team:80/stn-docker
  #   image: jfrog/pipelines-u18node
  #   tag: 10.21.0-jfrog
  #   repoSource: stn-docker-release-local
  # used by the Helm Chart resource
  repo: stn-helm
  repoPromotion1: stn-helm-release-local
  name: myapp
  version: 2.0.0
  artifactoryIntegration: artifactory_eu
  k8sIntegration: yann_k8s
  k8sNamespace: build-plane
  distributionIntegration: distribution_eu

K8s:
  pipelineName: k8s_deployment
  chart: 
    repo: urs-helm
    repoPromotion1: urs-helm-release-local
    name: myapp
    version: 0.1.0
  integration:
    artifactory: artifactory_eu
    k8s: yann_k8s
  namespace: build-plane

K8sResources:
  gitRepoHelm:
    name: src_code_helm
    gitProvider: my_github
    path: cyan21/su301
    branches:
      include: lab3_ok
    files:
      include: ^java\/cd\/k8s/.*\.yml
  chart:
    name: lab3_hc
  buildInfo:
    resourceName: lab3_bi_chart
    name: k8s_helm_chart
  buildInfoPromoted:
    resourceName: lab3_bi_chart_promoted

K8sSteps:
  publishHelm:
    name: lab3_publish_helm_chart
    path: java/cd/k8s/helm_chart/
    lint: true
    autoPublishBuildInfo: true
  deployHelm:
    name: lab3_deploy_helm_chart
  testApp:
    name: lab3_test_app
  promoteHelm:
    name: lab3_promote_helm_chart
    includeDependencies: false
    status: TEST_OK
    comment: passed non regression test
    copy: false



